/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora_bas_vec.h"
#include <math.h>

double *
sumar_1_svc(double x, double y,  struct svc_req *rqstp)
{
	static double  result;

	result = x + y;

	return &result;
}

double *
restar_1_svc(double x, double y,  struct svc_req *rqstp)
{
	static double  result;

	result = x - y;

	return &result;
}

double *
mutiplicar_1_svc(double x, double y,  struct svc_req *rqstp)
{
	static double  result;

	result = x * y;

	return &result;
}

double *
dividir_1_svc(double x, double y,  struct svc_req *rqstp)
{
	static double  result;

	result = x / y;

	return &result;
}

double *
potencia_1_svc(double x, double y,  struct svc_req *rqstp)
{
	static double  result;

	result = pow(x,y);

	return &result;
}

double *
raiz_1_svc(double x, struct svc_req *rqstp)
{
	static double  result;

	result = sqrt(x);

	return &result;
}

double *
seno_1_svc(double x,  struct svc_req *rqstp)
{
	static double  result;

	double num = x*M_PI / 180;
	result = sin(num);

	return &result;
}

double *
coseno_1_svc(double x,  struct svc_req *rqstp)
{
	static double  result;

	double num = x*M_PI / 180;
	result = cos(num);

	return &result;
}

double *
tangente_1_svc(double x,  struct svc_req *rqstp)
{
	static double  result;

	double num = x*M_PI / 180;
	result = tan(num);

	return &result;
}

double *
logbase_1_svc(double x,  struct svc_req *rqstp)
{
	static double  result;

	result = log10(x);

	return &result;
}

vec *
sumar_vectores_1_svc(datos vectores,  struct svc_req *rqstp)
{
	static vec  result;

	result.x = vectores.v1.v1_val[0] + vectores.v2.v2_val[0];
	result.y = vectores.v1.v1_val[1] + vectores.v2.v2_val[1];
	result.z = vectores.v1.v1_val[2] + vectores.v2.v2_val[2];

	return &result;
}

vec *
restar_vectores_1_svc(datos vectores,  struct svc_req *rqstp)
{
	static vec  result;

	result.x = vectores.v1.v1_val[0] - vectores.v2.v2_val[0];
	result.y = vectores.v1.v1_val[1] - vectores.v2.v2_val[1];
	result.z = vectores.v1.v1_val[2] - vectores.v2.v2_val[2];

	return &result;
}

double *
productoescalar_1_svc(datos vectores,  struct svc_req *rqstp)
{
	static double  result;

	result = vectores.v1.v1_val[0] * vectores.v2.v2_val[0] +
			 vectores.v1.v1_val[1] * vectores.v2.v2_val[1] +
			 vectores.v1.v1_val[2] * vectores.v2.v2_val[2];

	return &result;
}
