/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora_bas_vec.h"
#include <stdio.h>
#include <stdbool.h>
#include <string.h>

void
calculadora_1(char *host, char *tipo_calculadora, int num_op)
{
	CLIENT *clnt;
	double a,b,c,d,e,f;
	double *resultado;
	double *vector_res;
	datos vectores;
	vec *vector_resultado;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, BASICA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	// Operaciones de la calculadora basica
	if (num_op >= 1 && num_op <= 10){
		// Obtenemos los numeros, para las siguientes operaciones que usan dos datos:
		// Suma, resta, multiplicacion, division, potencia
		if(num_op >= 1 && num_op <= 5){
			printf("\nIntroduzca los dos numeros que desee para realizar la operacion (a y b): ");
			scanf("%lf", &a);
			scanf("%lf", &b);
		}else if(num_op >= 6 && num_op <= 10){ // Si no es una de las operaciones anteriores, solo obtenemos un dato
			printf("\nIntroduzca el numero que desee para realizar la operacion (a): ");
			scanf("%lf", &a);
		}

		if(num_op == 1){
			// Obtenemos los datos para realizar la suma...
			// printf("Introduzca los dos numeros a sumar (a + b): ");
			// scanf("%lf", &a);
			// scanf("%lf", &b);
			printf("Realizando la suma (%lf + %lf).....\n",a,b);

			// Realizamos la suma
			resultado = sumar_1(a,b, clnt);
			if (resultado == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}else if(num_op == 2){
			// Obtenemos los datos para realizar la resta...
			// printf("Introduzca los dos numeros a restar (a - b): ");
			// scanf("%lf", &a);
			// scanf("%lf", &b);
			printf("Realizando la resta (%lf - %lf).....\n",a,b);

			// Realizamos la resta
			resultado = restar_1(a,b, clnt);
			if (resultado == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}else if(num_op == 3){
			// Obtenemos los datos para realizar la multiplicacion...
			// printf("Introduzca los dos numeros a multiplicar (a * b): ");
			// scanf("%lf", &a);
			// scanf("%lf", &b);

			// Realizamos la multiplicacion
			printf("Realizando la multiplicacion (%lf * %lf).....\n",a,b);
			resultado = mutiplicar_1(a,b, clnt);
			if (resultado == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}else if(num_op == 4){
			// Obtenemos los datos para realizar la division...
			if(b == 0){
				do{
					printf("Introduzca un divisor valido (b > 0): ");
					scanf("%lf",&b);
					if(b == 0) printf("El divisor no puede ser 0.\n");
				}while(b == 0);
			}
			// Realizamos la division
			printf("Realizando la division (%lf / %lf).....\n",a,b);
			resultado = dividir_1(a,b, clnt);
			if (resultado == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}else if(num_op == 5){
			// Realizamos la potencia
			printf("Realizando la potencia (%lf^%lf).....\n",a);
			resultado = potencia_1(a,b, clnt);
			if (resultado == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}else if(num_op == 6){
			// Realizamos la raiz
			printf("Realizando la raiz ( sqrt(%lf) ).....\n",a,b);
			resultado = raiz_1(a, clnt);
			if (resultado == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}else if(num_op == 7){
			// Realizamos el seno
			printf("Realizando el seno (sin(%lf)).....\n",a);
			resultado = seno_1(a, clnt);
			if (resultado == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}else if(num_op == 8){
			// Realizamos el seno
			printf("Realizando el coseno (cos(%lf)).....\n",a);
			resultado = coseno_1(a, clnt);
			if (resultado == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}else if(num_op == 9){
			// Realizamos la tangente
			printf("Realizando la tangente (tan(%lf)).....\n",a);
			resultado = tangente_1(a, clnt);
			if (resultado == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}else if(num_op == 10){
			// Realizamos el logaritmo base 10
			printf("Realizando el logaritmo en base 10 (log(%lf)).....\n",a);
			resultado = logbase_1(a, clnt);
			if (resultado == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}		

		// Mostramos el resultado de la operacion
		printf("Operacion finalizada. Resultado: %lf\n\n", *resultado);
	}

	// Operaciones de la calculadora de vectores
	if(num_op >= 11 && num_op <= 14){
		// Obtenemos el contenido de los dos vectores
		printf("\nIntroduzca los dos vectores [ v1 = (a,b,c) y v2 = (d,e,f) ]\n");
		printf("v1: ");
		scanf("%lf", &a);
		scanf("%lf", &b);
		scanf("%lf", &c);

		// Reservamos la memoria, asignamos el tamaño del vector y asignamos valores de x, y, z
		vectores.v1.v1_val = malloc(MAX * sizeof(double));
		vectores.v1.v1_len = MAX;
		vectores.v1.v1_val[0] = a;
		vectores.v1.v1_val[1] = b;
		vectores.v1.v1_val[2] = c;

		printf("v2: ");
		scanf("%lf", &d);
		scanf("%lf", &e);
		scanf("%lf", &f);

		// Reservamos la memoria, asignamos el tamaño del vector y asignamos valores de x, y, z
		vectores.v2.v2_val = malloc(MAX * sizeof(double));
		vectores.v2.v2_len = MAX;
		vectores.v2.v2_val[0] = d;
		vectores.v2.v2_val[1] = e;
		vectores.v2.v2_val[2] = f;
		if(num_op == 12){
			// Realizamos la suma de vectores
			printf("Realizando la suma de dos vectores ( v1 + v2 )\n",a);
			vector_resultado = sumar_vectores_1(vectores, clnt);
			if (vector_resultado == (vec *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}else if(num_op == 13){
			// Realizamos la resta de vectores
			printf("Realizando la resta de dos vectores ( v1 - v2 )\n",a);
			vector_resultado = restar_vectores_1(vectores, clnt);
			if (vector_resultado == (vec *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}else if(num_op == 14){
			// Realizamos el producto escalar de vectores
			printf("Realizando el producto escalar de dos vectores ( v1 * v2 )\n",a);
			vector_res = productoescalar_1(vectores, clnt);
			if (vector_res == (double *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}

		if(num_op <= 13){
			printf("Operacion finalizada. Resultado: v3 = (%lf,%lf,%lf)\n\n", vector_resultado->x,vector_resultado->y,vector_resultado->z);
		}else if(num_op == 14){
			printf("El producto escalar de v1 y v2 es %lf\n\n",*vector_res);
		}
	
		// Liberamos la memoria de los vectores
		free(vectores.v1.v1_val);
		free(vectores.v2.v2_val);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	double a,
		   b;
	char *tipo_calculadora;
	int num_op;
	char *op;

	bool apagar = false;

	if (argc < 3 || argc > 3 ) {
		printf ("Uso de la calculadora: ./cliente localhost <tipo_calculadora>\n");
		printf ("Los tipos de calculadora (tipo_calculadora) actuales son: basica | vectores\n\n");
		exit (1);
	}

	host = argv[1];
	tipo_calculadora = argv[2];

	if(strcmp(tipo_calculadora,"basica") == 0 || strcmp(tipo_calculadora,"vectores") == 0){
		printf("\nCALCULADORA INICIADA. MODO: %s\n\n",tipo_calculadora);
	}else{
		printf("\nERROR, NO SE HA INTRODUCIDO NINGUN MODO DE CALCULADORA VALIDO");
		printf("\nAPAGANDO...\n");
		exit(1);
	}

	while(!apagar){
		if(strcmp(tipo_calculadora,"basica") == 0){
			printf("Operaciones disponibles: ");
			printf("\n1. Suma (a + b)\n2. Resta (a - b)\n3. Multiplicacion (a * b)\n4. Division (a / b)\n5. Potencia (a^b)\n");
			printf("6. Raiz cuadrada (sqrt(a))\n7. Seno (sin(a))\n8. Coseno (cos(a))\n9. Tangente (tan(a))\n10. Logaritmo base 10 (log(a))\n11. Apagar calculadora\n");
		}else if(strcmp(tipo_calculadora,"vectores") == 0){
			printf("Operaciones disponibles: ");
			printf("\n12. Suma de dos vectores ( (a,b,c) + (d,e,f) )\n13. Resta de  dos vectores ( (a,b,c) - (d,e,f) )\n14. Producto escalar de dos vectores ( (a,b,c) * (d,e,f) )\n11. Apagar calculadora\n");
		}

		printf("Indique el numero de la operacion que va a realizar: ");
		scanf("%d",&num_op);

		if(num_op < 1 || num_op > 14){
			do{
				printf("Introduzca un numero valido (1-14): ");
				scanf("%d",&num_op);
			}while(num_op < 1 || num_op > 14);
		}

		if(num_op != 11){
			calculadora_1(host,tipo_calculadora,num_op);
		}else apagar = true;

	}

	printf("\n\nAPAGANDO CALCULADORA...\n\n");

	exit (0);
}
